### ISSUE TITLE
OnDelete on Models.py

### ISSUE THREAD

**Issue by rokdd** [PsypherPunk/django-annotator#10]
I get the following error when migrating:
`  annotation = models.ForeignKey(Annotation, related_name="ranges")
TypeError: __init__() missing 1 required positional argument: 'on_delete'`

Nobody else?

**Comment by ajrbyers** [comment]
It looks like this package hasn't been updated for newer versions of Django that require the `on_delete` argument.

**Comment by PsypherPunk** [comment]
Wow, apologies but I never saw this. On the off chance anyone is still using this, I'm closing this as it should have been resolved.
